language: node_js
node_js: 
branches:
  only:
  - Dev
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
- npm install hexo@beta --save
- npm install hexo-deployer-git --save
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo clean
- hexo generate
after_success:
- git config --global user.name "zzgo"
- git config --global user.email "zzgoCC@gmail.com"
- sed -i'' "s~git@github.com:zernonhuang/zzgo.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/zernonhuang/zzgo.github.io.git~"
  _config.yml
- hexo deploy
env:
  global:
  - secure: o6UFDTzOWgSiubKvGvu9iOWh2PCzC+Lcue67ViWn4kb/ZwHBFRY+axgyRMxGxglZ8WaGurENYHVzJBLs66Cpnzy3p+d3RRbidO9HLBW+SNUBJ0JXDev/3tfXUvey5FUaUnkyjhXiqkkkJLjGfwDWfWXpemsuZTWWP1e1lo/aGwTJjnmzsVYJGHr9CPitkKx7w00D+Bi1Ck6M+LAaxJ50pzZDHzj6cZs/D4HQDjRKd/gsFZGoC23N7epuPJYIvSlVTLGmZAW2JYth0C++7c2igi0rJ59s0PU2QotJmDREZs4DWMKTnmVOiHvEU6qWiCrdE/hux4NxrT4FwpH2r6bFBcqGup1wZTfewdg/yl8+YajWQKkzZS8BWz6sHLY8OkDvilnAefDQdKSy486tCiRuPb0rv5YnusREGTiqlQ3L4b/R30yCO1711h/HUWRCLFTCjAk/7bewl+Lb+PEzdATHFmyYtSVxRtWZnA+jjgbStS2o+KL/Oamt6MPistmuzGzm7bjT1Gz0qFfaDy7wzksnkeMPmmq7Mjsh3UUxyEgIFPn+XrQLgyyCOpSCQEXwBEZzufS+/Nkl5ABbHkOEOgXXCqKEnL2s50t7zjRFOzSFHGhjHM9vmS00XeUB5LH6UDf5H25CDVhoyYqlvWIUy4Aay2ERdYM/OVsEocUjitYHzqE=
  - secure: C7y6BEXpWxR47DzsjQmFfLr/KVVJF6Vr2cafG8hlk4D4HdZjCzgCMsBEzi8pq5PMi/4oPJ1xHg6NGEEiU1bGyqUuCI8qv94i7F0y9PkvvS+MUkhSsUJ0i7WgiNvCCNXXhP7FqbYrHemHxsPQ8E3NeJnRQDRKDR3Zo1owIYp0j8dPIjQKYbiDxrRLl7qZJpu7azPcHcj9fB6gicdejKCbZaTpfiVNmbi+g0Yz6ZZeVUgTbwkskCfIxwZVP+V2F5oro2Nnc0W42cyJgN5aCHEh+FBuu0/BOlb0589a7Yrpzz1QcqTF8kMAHOWm0xrPIs7cJdFZ4V362qeqINsEnZa2Gw1eChFNoCxIgvGcrQuJ4bXvL/GsPJJukf2sL08FTLl7PDPelqzWdJ6b53Q0rGb9Q/LToFNwFq3vFzYgO1UqVhskUPyos7IbmtMXZiyLQZH1nRltls2+j4A9OmgzEfI9S2b9T1U5ESgAcyp5uR3ZcIVRMlJ29y2bjUpRn3+PhOP7aeJc/klfuV6rXjwDVRq+3PbLygzPIS/zU7KYOkaqyZjiFRJIsd7PNaewZJ8GB8yuFK6QO3mNtPEg+monAcoA8fKqusPkSA0NhTOzU+fJonmBNgEWRzFcVBBJVPgILPu51CWMSWT8Ay2y1m8q+TZZ3WVHvH0EmujO2noTyyKvh1I=
