os: osx
language: node_js
node_js: 
branches:
  only:
  - Dev
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
#- npm install
- npm install hexo --save
- npm install hexo-renderer-stylus --save
- npm install hexo-deployer-git --save
install:
- npm install
script:
#- git submodule init
#- git submodule update
#- hexo clean
- hexo generate
after_success:
- git config --global user.name "zenonhuang"
- git config --global user.email "zzgocc@gmail.com"
- sed -i'' "s~git@github.com:zenonhuang/zenonhuang.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/zenonhuang/zenonhuang.github.io.git~"
  _config.yml
- hexo deploy
env:
  global:
  - secure: C7y6BEXpWxR47DzsjQmFfLr/KVVJF6Vr2cafG8hlk4D4HdZjCzgCMsBEzi8pq5PMi/4oPJ1xHg6NGEEiU1bGyqUuCI8qv94i7F0y9PkvvS+MUkhSsUJ0i7WgiNvCCNXXhP7FqbYrHemHxsPQ8E3NeJnRQDRKDR3Zo1owIYp0j8dPIjQKYbiDxrRLl7qZJpu7azPcHcj9fB6gicdejKCbZaTpfiVNmbi+g0Yz6ZZeVUgTbwkskCfIxwZVP+V2F5oro2Nnc0W42cyJgN5aCHEh+FBuu0/BOlb0589a7Yrpzz1QcqTF8kMAHOWm0xrPIs7cJdFZ4V362qeqINsEnZa2Gw1eChFNoCxIgvGcrQuJ4bXvL/GsPJJukf2sL08FTLl7PDPelqzWdJ6b53Q0rGb9Q/LToFNwFq3vFzYgO1UqVhskUPyos7IbmtMXZiyLQZH1nRltls2+j4A9OmgzEfI9S2b9T1U5ESgAcyp5uR3ZcIVRMlJ29y2bjUpRn3+PhOP7aeJc/klfuV6rXjwDVRq+3PbLygzPIS/zU7KYOkaqyZjiFRJIsd7PNaewZJ8GB8yuFK6QO3mNtPEg+monAcoA8fKqusPkSA0NhTOzU+fJonmBNgEWRzFcVBBJVPgILPu51CWMSWT8Ay2y1m8q+TZZ3WVHvH0EmujO2noTyyKvh1I=
