language: node_js
node_js:
 # - '0.12.5'
  - stable
 # - '5.8'

branches:
  only:
  - Dev
  
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
#- npm install hexo@3.2.0 -g
- npm install -g hexo-cli
#- npm install hexo-renderer-stylus --save
#- npm install -g minimatch@3.0.2
- npm install hexo@beta --save
- npm install hexo-deployer-git --save

install:
- npm install
#- npm update clean-css

script:
- git submodule init
- git submodule update
- hexo clean
- hexo generate

after_success:
- git config --global user.name "zzgo"
- git config --global user.email "zzgoCC@gmail.com"
- sed -i'' "s~git@github.com:zzgo/zzgo.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/zzgo/zzgo.github.io.git~"
  _config.yml
- hexo deploy
env:
  global:
    secure: YQkPNZU3EnjfHDZpxnQAa0/s7aohcBNpx8WIE0A8QS91ZnxYBx5yVjRPKtzkgbqCXOxMWvl8k715MW+4mAuy0R4USjYnqRUd2BisJF0NhQUl0uJwi/QgsrmPrWpajWiUeL2X9SbZDnccf4zJ9DIyKU8u328zv6xNteVrd5LFqaFaViSXmjrKgREYDbDO4aMcgQiM3U3yQppcHQEzEFkhbuUNPvHuVCo7e8qp6qrVlj/u693zWlilIHwMtGSMQoCkuXVMz+r53vjitwpciE1eX6NCUf+atxzRZ6fd2EIpVhncenW9xNrif4FSewOCMTpCQok2Yln1jfJ5lfKyrIYoPz7eGjOuVMDvypdlD5yuaHiughkSoFveDfjduWutYrCJnwxGXEr89WevX1sAwpefwScpZiHunhwsdC52qWwZ7309wWNalnrmLFEisCHXEjWZxA8skvhGrLanAtrWzcwdIQOaNRstgY/z50jz2kDAwkCVM1QrfWrQ8Lkb9DLlBwu7fPTu4YEMMIO7tXsBBjKHaoH60kJm2CB3JlYk1F+7NGyCcJ8NLDiHRwrJ3dlaCCN7+4Jj6QwSFNPxkO0ESGlGSYHVg5/J877r7qlDW5SlcymnII9pyXivw+pj1Ho4CyJMvu37gMsJjWrWtr1NOLDM4IKeea7wrH2DnCfNWN2wM8M=
